### ISSUE TITLE
about license gpl v3, could be lgpl v2 or more open license?

### ISSUE THREAD

**Issue by bung87** [mock-up/ffmpeg.nim#3]
ffmpeg itself use lgpl v2 which useful for close source software link it as library, which is common use case , however this wrapper use a gpl v3 license.

**Comment by momeemt** [comment]
@bung87
Hello. I've been looking for a way to get my hands on a new job. Thanks for pointing this out to me.
I didn't really understand the license when I created the library; I checked the FFmpeg itself and understood that it should be licensed under the LGPL-2.1-or-later.
From the next version, ffmpeg.nim will be granted LGPL-3.0.

**Comment by momeemt** [comment]
https://github.com/mock-up/ffmpeg.nim/pull/10

I have corrected the PR here.
